name: Log Job Summaries
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: | # マークダウンテキストをジョブサマリーへ出力
          echo "## Title :rocket:" >> "${GITHUB_STEP_SUMMARY}"
          echo "- file line" >> "${GITHUB_STEP_SUMMARY}"
          echo "- second line" >> "${GITHUB_STEP_SUMMARY}"