name: Log Group
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::group::Show environmanet variables" # ロググループを開始
          printenv
          echo "::endgroup::" # ロググループを終了