name: Sequential Jobs
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "First job done"
  second-job:
    runs-on: ubuntu-latest
    needs: [first-job]  # first-jobを待ってから実行
    steps:
      - run: sleep 10 && echo "Second job done"
  third-job:
    runs-on: ubuntu-latest
    needs: [second-job] # second-jobを待ってから実行
    steps:
      - run: sleep 10 && echo "Third job done"