name: Share Job Data
on: push
jobs:
  before-job:
    runs-on: ubuntu-latest
    steps:
      - id: generate  # ステップIDを指定
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}" # ステップレベルの出力値を設定
    outputs:
      result: ${{ steps.generate.outputs.result }} # ジョブレベルの出力値
  after-job:
    runs-on: ubuntu-latest
    needs: before-job # before-jobを待ってから実行
    steps:
      - env:
          RESULT: ${{ needs.before-job.outputs.result }} # before-jobの出力値を環境変数に設定
        run: echo "${RESULT}" # before-jobの出力値を表示